version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - aws s3 cp ./src/ s3://$WEBSITE_BUCKET --recursive
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths="/*" 
